import core
from cryoemcnb.constants import ACTION_COPY_DATA, ACTION_GENERATE_METADATA, ACTION_SEND_METADATA, ACTION_PRINT_PROJECT, ACTION_PROVIDE_RAW_DATA_LINUX, ACTION_PROVIDE_RAW_DATA_WINDOWS
from cryoemcnb.actions import copy_data, generate_metadata, send_metadata, print_project, provide_raw_data_windows, provide_raw_data_linux


class Plugin(core.Plugin):

    @classmethod
    def define_args(cls):
        cls.define_arg(ACTION_COPY_DATA, {
            'help': {'usage': '--raw-data-path RAW_DATA_PATH',
                     'epilog': '--raw-data-path /data/Talos/projectx'},
            'args': {
                'raw-data-path': {'help': 'path of the raw data',
                                  'required': True
                                  }
            }
        })

        cls.define_arg(ACTION_PROVIDE_RAW_DATA_WINDOWS, {
            'help': {'usage': '--irods-ticket IRODS_windows_ticket',
                     'epilog': ' --irods-ticket $scriptPath = "rods_fetch_win.ps1"; (Invoke-WebRequest -UseBasicParsing "https:xxx.ps1").Content | Out-File $scriptPath -Encoding UTF8; & powershell -ExecutionPolicy Bypass -File $scriptPath --host xx-xx.xx.xx.es --collection "/xxZone/000153_ATLAS" --ticket "xxxxxx" --output_dir "2026153_ATLAS"; Remove-Item $scriptPath'},
            'args': {
                'irods-ticket': {
                    'help': 'ticket generated by IRODS to download the data on a Windows OS',
                    'required': True
                    }
            }
        })

        cls.define_arg(ACTION_PROVIDE_RAW_DATA_LINUX, {
            'help': {'usage': 'irods-ticket IRODS_linux_ticket',
                     'epilog': 'irods-ticket "curl -sSfL ".../irods_fetch_unix.sh" | bash -s -- --host "xxxx.xx.xx.es" --collection "/xxZone/home/DATA_03" --ticket "xxxxxxxxx" --output_dir "2026_06_Data_03""'
                    },
            'args': {
                'irods-ticket': {'help': 'ticket generated by IRODS to download the data on a Linux OS',
                                  'required': True
                                  },
            }
        })

        cls.define_arg(ACTION_GENERATE_METADATA, {
            'help': {'usage': '--metadata-path METADATA_PATH',
                     'epilog': '--metadata-path /home/user/ScipionUserData/projects/Project_scipion/Runs/003083_ProtOSCEM/extra'},
            'args': {
                'metadata-path': {'help': 'path of the metadata generated with the OSCEM_json protocol',
                                  'required': True
                                  }
            }
        })

        cls.define_arg(ACTION_SEND_METADATA, {
            'help': {'usage': '--visit-id VISIT_ID',
                     'epilog': '--visit-id 2'},
            'args': {
                'visit-id': {'help': 'ARIA visit id',
                             'required': True
                             }
            }
        })

    @classmethod
    def define_methods(cls):
        cls.define_method(ACTION_COPY_DATA, copy_data.perform_action)
        cls.define_method(ACTION_PROVIDE_RAW_DATA_LINUX, provide_raw_data_linux.perform_action)
        cls.define_method(ACTION_PROVIDE_RAW_DATA_WINDOWS, provide_raw_data_windows.perform_action)
        cls.define_method(ACTION_GENERATE_METADATA, generate_metadata.perform_action)
        cls.define_method(ACTION_SEND_METADATA, send_metadata.perform_action)
        cls.define_method(ACTION_PRINT_PROJECT, print_project.perform_action)
